<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Nexora.Command</PackageId>
    <Version>1.0.1</Version>
    <Authors>MCDaxia</Authors>
    <Company>Nexora studio</Company>
    <Description>Minecraft like command tree building and execution in .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
